### PR TITLE
Fix nvm failure in toolchain/installLinux.sh - Closes #225

### LINKED ISSUE #225: installLinux.sh script will fail to run the command "nvm install v6.10.1"
The `install_linux.sh` should check and install the system the packages that are needed to run lisk-build. The problem is that in `shared.sh` the definition for `cmd_exec` is running via `bash -c`
but `nvm` is not a command but bash function, hence it will not run from a bash script. We could run it without the `cmd_exec`.

### Expect behaviour
`nvm` should be installed to the correct version.

### Actual behaviour
Running the script results with the error:
```
bash: nvm: command not found
```

### Steps to reproduce
Start a fresh machine running linux:

```
git clone https://github.com/LiskHQ/lisk-build.git
cd toolchain/
chmod u+x install_linux.sh
./install_linux.sh
```

### PR DESCRIPTION
**Pull request by Nazgolze**
Closes #225

### CODE REVIEW

**Comment by Nazgolze** [comment]
Shellcheck doesn't like it. though it  is a copy/paste of what the nvm script recommends to do.

**Comment by ghost** [comment]
It's just that shellcheck cannot find the sourced file and thus cannot check it. You need to add a comment for shellcheck to find it (`# shellcheck source=path/to/nvm.sh`) or ignore it (`# shellcheck source=/dev/null`)

**Comment by Nazgolze** [comment]
@fchavant You beat me to it :-). I was thinking of going with the ignore option, though technically it should be /home/lisk/.nvm/nvm.sh

**Comment by ghost** [comment]
I think we should ignore: we're not going to modify `nvm.sh` even if shellcheck reports warnings in that file.

**Review by karmacoma — DISMISSED** [review]

**Review by karmacoma — APPROVED** [review]

**Pull request merged**
