### PR TITLE
Add lock file option

### PR DESCRIPTION
**Pull request by mrv777**
Added an option to use a lock file to make sure the script isn't running twice at a given time.  Gr33nDrag0n's idea, I just implemented it

### CODE REVIEW

**Comment by mrv777** [comment]
I wanted to write this and add it before I forgot.  I didn't get to test it personally yet though as I don't have time before work.  Sorry about that

**Comment by Gr33nDrag0n69** [comment]
I'm at work, I will add more infos on the idea tonight

**Comment by Gr33nDrag0n69** [comment]
Look like it's exactly what I was saying. Only thing I see that should be a but different is the echo commands should be like this one to make it like the others in the scripts

echo -e "\nMyMessage" instead of echo "MyMessage"

**Comment by Gr33nDrag0n69** [comment]
The goal of this modification is to allow the auto-sanpshot cronjob to run every 5 minutes instead of a predefined schedule like each 6 hours. This way the job could run every 5 minutes for example and only create a new snapshot when another one isn't already running. More efficient and remove the need for schedule update from time to time.

**Comment by Isabello** [comment]
I have a better idea than to create more files.

We can leverage the existing PID_FILE in lisk.sh and check_status.

```
check_status() {
  if [ -f "$PID_FILE" ]; then
  read PID < "$PID_FILE" 2>&1 > /dev/null
  fi
  if [ ! -z "$PID" ]; then
    ps -p "$PID" > /dev/null 2>&1
    STATUS=$?
  else
    STATUS=1
  fi
  if [ -f "$PID_FILE" ] && [ ! -z "$PID" ] && [ "$STATUS" == 0 ]; then
    echo '√ Lisk is running as PID: '"$PID"
    blockheight
    return 0
  else
    echo "X Lisk is not running."
    return 1
  fi
}
```

As we see here if lisk isnt running we return a code. We can modify this to provide an exit code when not running and read that from lisk_snapshot.sh instead.

This is a cleaner way to do it than checking the age of the lockfile

**Comment by Gr33nDrag0n69** [comment]
Not sure since PID isn't necessarily cleanup. (Why the 24 hours safety at the end).

Creating a empty file just testing if it exist isn't that much new files.

I want to add the test to determine if a snapshot is in progress, not if main lisk client is currently running. So PID not a good idea in that case.

**Comment by Isabello** [comment]
The pid checks the specific client, not all clients.

**Comment by Gr33nDrag0n69** [comment]
so it would not take care of the lisk process launched by lisk.sh and just the process launched by lisk_snapshot.sh (lisk client in snapshot mode) If this is the case, then yes it could work and would limit file creation, But I would still leave a timeout limit that remove the flag in case it has been there for to long.

**Comment by Gr33nDrag0n69** [comment]
Just saw you say checking the age of blockfile is not clean, it's just a safety.

The real test is just a file exist test

**Comment by Isabello** [comment]
We can create a system that does the following:

Checks if a snapshot instance is running based on the PID status
Checks the log file to see if it was updated recently as a fail safe
Cleans up the process if its too old

**Comment by Gr33nDrag0n69** [comment]
Yeah, that would work with more work. The lock file i proposed to MrV was meant to be simple and effective. (very limited code modification)

**Comment by Isabello** [comment]
Im fine with doing the work if we get a more robust solution :)

**Comment by Gr33nDrag0n69** [comment]
If you see a better way, go for it. The main goal being that we can put a schedule task every 5 minutes for the snapshots and that it skip new snap if one already in progress or stalled for too long. I think you understand well so I trust your solution.

**Comment by Gr33nDrag0n69** [comment]
The lock file was quick and clever fix.

**Comment by Isabello** [comment]
Yes that sounds great. Let me take some time on this one. I am revisiting lisk-build scripts this week anyways

**Comment by Gr33nDrag0n69** [comment]
Ok, please let us know when this is ready for testing on testnet. I would like to push this asap on mainnet before i package the script for latest.gz. I feel that it might be a game changer for the schedule we used behind. Anyway, thanxs for giving it some leverage.

**Comment by Gr33nDrag0n69** [comment]
Just thinking out loud, if MrV code do the job, why not accept it for now and replace it when a better version is available ?

**Comment by Isabello** [comment]
Im looking at this today.

**Comment by Isabello** [comment]
@mrv777 @Gr33nDrag0n69 

see this solution here. let me know if its in line with what you are expecting.

https://github.com/LiskHQ/lisk-build/commit/4f8b971e6c737e20092eb60b9cce4f2cbb93a52e

**Comment by Isabello** [comment]
This pull request is superceded by https://github.com/LiskHQ/lisk-build/pull/68

**Pull request closed without merging**
